gcc vs-arraygen.c -o vs-arraygen
nasm vs-context_get.asm -o vs-context_get.o
nasm vs-context_set.asm -o vs-context_set.o
echo "// This file is automatically generated from vs-context_get.asm" > vs-context_get.inc
echo "// This file is automatically generated from vs-context_set.asm" > vs-context_set.inc
cat vs-context_get.o | ./vs-arraygen >> vs-context_get.inc
cat vs-context_set.o | ./vs-arraygen >> vs-context_set.inc
rm vs-arraygen
rm vs-context_get.o
rm vs-context_set.o